# Fish shell configuration
shell /opt/homebrew/bin/fish

# Fonts
font_family      family="JetBrainsMono Nerd Font Mono"
font_size        13
line_height      1.2
bold_font        auto
italic_font      auto
bold_italic_font auto

# Transparency
background_opacity 0.95
background_blur 32

# Border
window_margin_width 8
